### ISSUE TITLE
Controller Listener

### ISSUE THREAD

**Issue by dbknv** [SergejPr/NooLite-F#2]
Добрый день, 
Спасибо за огромную работу по написанию данного модуля. Подскажите как правильно использовать Controller Listener и одновременной отправки Send команд различным блокам ? 

Простое выполнение кода из примера: https://github.com/SergejPr/NooLite-F#using-controller-listener
всегда заканчивается так
```
{1: [<__main__.MyRemoteController object at 0x054A2EB0>]}
{1: [<__main__.MyRemoteController object at 0x054A2EB0>], 2: [<__main__.MySensor object at 0x054A2ED0>]}

Process finished with exit code 0
```

Хотя я думаю, что мой скрипт должен перейти в бесконечное выполнение.

**Comment by SergejPr** [comment]
Добрый день,

Извиняюсь за задержку с ответом.
Если Вы ни чего не добавляли к скрипту с примером то это вполне ожидаемый результат. После выполнения последней строчки скрипта происходит его завершение, то есть по сути мы выходим из программы. 

Самый простой способ заставить данный скрипт выполняться бесконечно - это добавить в конце бесконечный цикл:

```
while True:
    sleep(60)

``` 

Таким образом Вы предотвратите выход из скрипта и он будет выполняться бесконечно, до тех пор пока вы его сами не остановите.

**Comment by SergejPr** [comment]
PS: Исправил ошибки в примерах, вместо ModuleType должно быть ModuleMode.

**Comment by dbknv** [comment]
Спасибо за разъяснение! Думаю что в пример нужно добавить:
```
while True:
    time.sleep(60)
```

**Comment by SergejPr** [comment]
Добавил.
